### ISSUE TITLE
Send couple of first lines as preview

### ISSUE THREAD

**Issue by Oreolek** [Roliga/discord_webhook#1]
It would be very useful to see the first 2-3 lines (~150 characters) of the article as a preview. Lots of posts don't have meaningful titles.

**Comment by Roliga** [comment]
Good idea! Article content does contain html tags which would need to be dealt with. Perhaps just stripping them would be enough, but that would mean a lot of line breaks would go missing. Maybe that's good enough though.

The article content could then go either in *italics* under the title/url, or in a code block. The latter may look nicer but would prevent any links in the content from being clicked.

I'll look into adding this soon, maybe with an option to set how much of the article to include. What do you think?

**Comment by Oreolek** [comment]
Stripping would be enough. Just take the first sentence.

**Comment by Roliga** [comment]
Pushed some new changes to master. Let me know if it works for you!

**Comment by Oreolek** [comment]
So far it's good.
